ALTER TABLE t_p43245144_car_buying_hk_1.leads 
ADD COLUMN IF NOT EXISTS telegram_sent BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS telegram_error TEXT,
ADD COLUMN IF NOT EXISTS max_sent BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS max_error TEXT;